<?php
/**
 * Created by PhpStorm.
 * User: MAURÍCIO
 * Date: 05/12/2014
 * Time: 03:44
 */

$con = new Controller();
$redirectorHelper = new RedirectorHelper();

?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-br" xml:lang="pt-br">
<head>
    <meta http-equiv="Content-Type" content="text/html" charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="LS Admin Painel" />
    <meta name="author" content="Maurício Falbo" />
    <title> </title>

    <!--[if lte IE 8]>
    <meta HTTP-EQUIV="REFRESH" content="0; url=lte-ie8.html">
    <![endif]-->

</head>
<body>
    <?php require_once( $file ) ?>
</body>

</html>