<?php
/**
 * Created by PhpStorm.
 * User: MAURÍCIO
 * Date: 12/12/2014
 * Time: 02:12
 */

$con = new Controller();
$redirectorHelper = new RedirectorHelper();

?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-br" xml:lang="pt-br">
<head>
    <meta http-equiv="Content-Type" content="text/html" charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <?php $con->link(TEMANEON."assets/images/favicon.png")?>

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Maurício Falbo" />

    <title><?php echo $con->title?></title>


    <?php
        $con->stylesheet( TEMANEON . "assets/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css");
        $con->stylesheet( TEMANEON . "assets/css/font-icons/entypo/css/entypo.css");
        $con->stylesheet( "http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic");
        $con->stylesheet( TEMANEON . "assets/css/bootstrap.css");
        $con->stylesheet( TEMANEON . "assets/css/neon-core.css");
        $con->stylesheet( TEMANEON . "assets/css/neon-theme.css");
        $con->stylesheet( TEMANEON . "assets/css/neon-forms.css");
        $con->stylesheet( TEMANEON . "assets/css/custom.css");

        $con->jsScript( TEMANEON . "assets/js/jquery-1.11.0.min.js");
    ?>

    <!--[if lt IE 9]> <?php $con->jsScript( TEMANEON . "assets/js/ie8-responsive-file-warning.js"); ?> <![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <?php $con->jsScript( "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js" ); ?>
    <?php $con->jsScript( "https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js" ); ?>
    <![endif]-->

</head>

<body class="page-body skin-white login-page login-form-fall">

<!-- This is needed when you send requests via Ajax -->
<script type="text/javascript">
    var baseurl = "";

</script>

<div class="login-container">

    <div class="login-header login-caret">

        <div class="login-content">

            <a href="<?php $redirectorHelper->getLink("index","index",true); ?>" class="logo">
                <?php $con->image(TEMANEON."assets/images/logo.png")?>
            </a>

            <p class="description">Digite login e senha para entrar no sistema</p>

            <!-- progress bar indicator -->
            <div class="login-progressbar-indicator">
                <h3>43%</h3>
                <span>Fazendo o login...</span>
            </div>
        </div>

    </div>

    <div class="login-progressbar">
        <div></div>
    </div>

    <div class="login-form">

        <div class="login-content">

            <div class="form-login-error">
                <h3>Login Falhou</h3>
                <p>Certifique-se de que login e senha foram digitados corretamente.</p>
            </div>

            <form method="post" role="form" id="form_login">

                <div class="form-group">

                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="entypo-user"></i>
                        </div>

                        <input type="text" class="form-control" name="username" id="username" placeholder="Login" autocomplete="off" />
                    </div>

                </div>

                <div class="form-group">

                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="entypo-key"></i>
                        </div>

                        <input type="password" class="form-control" name="password" id="password" placeholder="Senha" autocomplete="off" />
                    </div>

                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block btn-login">
                        <i class="entypo-login"></i>
                        Logar
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Bottom Scripts -->

<?php
    $con->jsScript( TEMANEON . "assets/js/gsap/main-gsap.js");
    $con->jsScript( TEMANEON . "assets/js/jquery-ui/js/jquery-ui-1.10.3.minimal.min.js");
    $con->jsScript( TEMANEON . "assets/js/bootstrap.js");
    $con->jsScript( TEMANEON . "assets/js/joinable.js");
    $con->jsScript( TEMANEON . "assets/js/resizeable.js");
    $con->jsScript( TEMANEON . "assets/js/neon-api.js");
    $con->jsScript( TEMANEON . "assets/js/jquery.validate.min.js");
    $con->jsScript( TEMANEON . "assets/js/neon-login.js");
    $con->jsScript( TEMANEON . "assets/js/neon-custom.js");
    $con->jsScript( TEMANEON . "assets/js/neon-demo.js");
?>
</body>
</html>