<?php
/**
 * Created by PhpStorm.
 * User: MAURÍCIO
 * Date: 10/12/2014
 * Time: 16:30
 */

$con = new Controller();
$redirectorHelper = new RedirectorHelper();
?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-br" xml:lang="pt-br">
<head>
    <meta http-equiv="Content-Type" content="text/html" charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <?php $con->link(TEMANEON."assets/images/favicon.png")?>

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Maurício Falbo" />

    <title><?php echo $con->title?></title>

    <!--[if lt IE 9]> <?php $con->jsScript( TEMANEON . "assets/js/ie8-responsive-file-warning.js"); ?> <![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <?php $con->jsScript( "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js" ); ?>
    <?php $con->jsScript( "https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js" ); ?>
    <![endif]-->
</head>
<body class="page-body" data-url="">
<table width="800" border="1" cellspacing="0" cellpadding="0">
    <tr>
        <td width="300" height="150" align="center" valign="middle"><image src="../images/logo1-300x90.png"  /></td>
        <td width="250" align="center" valign="middle"><p>Studio Prime Audiovisual ltda.<br />
                Rua Senador Soares, 55. Vila Isabel
                <br />
                Cnpj: 102.89065/0001-52<br />
                Tel: (21) 2578-4656</p></td>
        <td width="250" align="center" valign="middle"><image src="../barcode/generatebarcode.php?barcode=<?php echo substr($lista_codigo,0,-1); ?>" width="200" height="45" /><br /><?php echo $lista_codigo; ?></td>
    </tr>
    <tr valign="top">
        <td width="300" height="50" align="left">Nome:<br /><?php echo $lista_nome; ?></td>
        <td width="250" align="left">Data de retirada:<br /><?php echo $lista_retirada_ageita; ?></td>
        <td width="250" align="left">Data de retorno:<br /><?php echo $lista_retorno_ageita; ?></td>
    </tr>
    <tr valign="top">
        <td width="300" height="50" align="left">Responsavel:<br /><?php echo $lista_resp_nome; ?></td>
        <td width="250" align="left">Numero de items:<br /><?php echo $itemscount; ?></td>
        <td width="250" align="left">Valor Total:<br /><?php echo number_format ($valortotallista,2,",","."); ?></td>
    </tr>
    <tr valign="top">
        <td width="300" height="50" align="left">Cobertura:<br /><?php echo $cobertura; ?></td>
        <td width="250" align="left">Equipe:<br /><?php echo $equipe; ?></td>
        <td width="250" align="left">Local/Transporte:<br /><?php echo $localtrans; ?></td>
    </tr>
</table>
<table width="800" border="1" cellspacing="0" cellpadding="0">
    <tr>
        <td height="100" align="left" valign="top">Obs:<br /><font color="#FF0000"><?php echo $lista_obs; ?> </font></td>
    </tr>
</table>
<table width="800" border="1" cellspacing="0" cellpadding="0">
    <tr>
        <td height="30" align="center" valign="middle">Conteúdo da lista de locação</td>
    </tr>
</table>
<table width="800" border="1" cellspacing="0" cellpadding="0">
    <tr>
        <td width="270" align="center" valign="middle">Nome</td>
        <td width="80" align="center" valign="middle">Marca</td>
        <td width="100" align="center" valign="middle">Lacre</td>
        <td width="50" align="center" valign="middle">Ptr</td>
        <td width="50" align="center" valign="middle">Local</td>
        <td width="50" align="center" valign="middle">Qtd</td>
        <td width="100" align="center" valign="middle">Obs</td>
        <td width="100" align="center" valign="middle">Valor</td>
    </tr>
    <?php
    echo $tabelaitems;
    ?>
</table>
<script>
    window.print();
</script>
</body>
</html>