<?php
/**
 * Created by PhpStorm.
 * User: MAURÍCIO
 * Date: 10/12/2014
 * Time: 16:30
 */

$con = new Controller();
$redirectorHelper = new RedirectorHelper();
?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-br" xml:lang="pt-br">
<head>
    <meta http-equiv="Content-Type" content="text/html" charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <?php $con->link(TEMANEON."assets/images/favicon.png")?>

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="Maurício Falbo" />

    <title><?php echo $con->title?></title>

    <?php
    $con->stylesheet( TEMANEON . "assets/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css");
    $con->stylesheet( TEMANEON . "assets/css/font-icons/entypo/css/entypo.css");
    $con->stylesheet( "http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic");
    $con->stylesheet( TEMANEON . "assets/css/bootstrap.css");

    $con->stylesheet( TEMANEON . "assets/css/custom.css");


    $con->jsScript( TEMANEON . "assets/js/jquery-1.11.0.min.js");
    ?>

    <!--[if lt IE 9]> <?php $con->jsScript( TEMANEON . "assets/js/ie8-responsive-file-warning.js"); ?> <![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <?php $con->jsScript( "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js" ); ?>
    <?php $con->jsScript( "https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js" ); ?>
    <![endif]-->
</head>
<body class="page-body" data-url="">

    <?php require_once( sprintf("%s/tabela.phtml",LAYOUT) ) ?>

<script>
    window.print();
</script>
</body>
</html>