<h2>Cadastrar Funcionários</h2>
<hr/>
<form method="post" action="<?php $redirectorHelper->getLink("usuario", "cadastrar", true); ?>" id="field-form">

    <div class="panel panel-invert panel-shadow form-actions">
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                </div>
                <div class="col-md-6 text-right">

                    <a href="<?php $redirectorHelper->getLink("usuario","menu",true); ?>" class="btn btn-default btn-icon btn-lg icon-left">Voltar<i class="entypo-left-open"></i></a>
                    <button type="button" class="btn btn-green btn-icon btn-lg" id="field-botao">Salvar<i class="entypo-check"></i></button>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            <div class="tocify-content">
                <div class="panel panel-default panel-shadow">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <h4>Dados do Funcionário</h4>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            <div class="col-md-12 tooltip-primary">
                                <div class="col-md-12">
                                    <label for="field-nome" class="control-label">Nome</label>
                                    <input type="text" name="nome" class="form-control" id="field-nome"
                                           placeholder="Nome" data-validate="required" value="" >
                                    <br/>
                                </div>

                                <div class="col-md-12">
                                    <label for="field-sobrenome" class="control-label">Sobrenome</label>
                                    <input type="text" name="sobrenome" class="form-control" id="field-sobrenome"
                                           placeholder="Sobrenome" data-validate="required" value="" >
                                    <br/>
                                </div>

                                <div class="col-md-12">
                                    <label for="field-cpf" class="control-label">CPF</label>
                                    <input type="text" name="cpf" class="form-control" id="field-cpf"
                                           placeholder="CPF" data-validate="required" value="" data-mask="999.999.999-99">
                                    <br/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<script>
    $(document).ready(function () {

        $("input").blur(function(){
            if($(this).val() == "")
            {
                $(this).css({"border" : "1px solid #F00"});
            }
            else
            {
                $(this).css({"border" : "1px solid #4cbf15"});
            }
        });

        $("#field-botao").click(function(){
            var cont = 0;
            $("#field-form input").each(function(){
                if($(this).val() == "")
                {
                    $(this).css({"border" : "1px solid #F00"});
                    cont++;
                }
            });
            if(cont == 0)
            {
                $("#field-form").submit();
            }
        });
    });
</script>
