<h2>Criar Lista</h2>
<hr/>
<form method="post" action="<?php $redirectorHelper->getLink("lista", "cadastrar", true); ?>">
    <input type="hidden" id="field-url" value="<?php $redirectorHelper->getLink("lista", "verificarItem", true); ?>" >
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            <div class="tocify-content">
                <div class="panel panel-default panel-shadow">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <h4>Dados da Lista</h4>
                        </div>
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            <div class="col-md-12 tooltip-primary">
                                <div class="col-md-12">
                                    <br/>
                                    <label for="field-nome" class="control-label">Nome</label>
                                    <input type="text" name="nome" class="form-control" id="field-nome"
                                           placeholder="Nome" data-validate="required" value="">
                                    <br/>
                                    <label for="field-nome" class="control-label">Cliente</label>
                                    <input type="text" name="marca" class="form-control" id="field-marca"
                                           placeholder="Marca" data-validate="required" value="">
                                    <br/>
                                    <label for="field-nome" class="control-label">Observações</label>
                                    <textarea name="obs" class="form-control" id="field-obs"
                                              placeholder="Observações"></textarea>

                                    <br/>
                                    <?php /*<label for="field-nome" class="control-label">Itens</label>
                                    <textarea name="obs" class="form-control" id="field-codigo" rows="10" disabled style="font-size: 18px; color: #000;"></textarea>*/?>
                                    <table class="table table-hover" id="table-codigo">
                                        <thead>
                                            <tr>
                                                <th>Cógido</th>
                                                <th>Nome</th>
                                                <th>Ações</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        </tbody>
                                    </table>
                                </div>

                                <br/>
                                <button type="submit" class="btn btn-green btn-icon">Cadastrar <i class="entypo-check"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    $(document).ready(function () {
        var barcode = "";
        $(document).keydown(function (e) {
            var code = (e.keyCode ? e.keyCode : e.which);
            if (code == 13)// Enter key hit
            {
                if (barcode.length == 13) {

                    $.post(
                        $("#field-url").attr("value"),{code: barcode},
                        function(data)
                        {
                            if(data == 1)
                            {
                                $("#field-codigo").val("Item não encontrado!");
                            }
                            else
                            {

                                console.log(data);

                                $("#table-codigo tbody").append(
                                    "<tr>"+
                                        "<td>"+ data +"</td>"+
                                        "<td>"+ +"</td>"+
                                        "<td>TESTE</td>"+
                                    "</tr>"
                                );
                            }
                        });

                    //$("#field-codigo").append(barcode);

                    barcode = "";
                }
                else if (barcode.length == 8) {
                    //$("#field-codigo").val("");
                    barcode = "";
                }
            }
            else {
                barcode = barcode + String.fromCharCode(code);
            }
        });
    });
</script>