<h2>Menu de Lista</h2>
<hr/>
<div class="panel panel-invert panel-shadow form-actions">
    <div class="panel-body">
        <div class="row">
            <div class="col-md-6">
            </div>
            <div class="col-md-6 text-right">
                <a href="<?php $redirectorHelper->getLink("lista","menu",true); ?>" class="btn btn-default btn-icon btn-lg icon-left">Voltar<i class="entypo-left-open"></i></a>
            </div>
        </div>
    </div>
</div>
<?php $this->tabela(); ?>